### ISSUE TITLE
Rails 5 "undefined method 'helper_method' for ActionController::API::Class

### ISSUE THREAD

**Issue by stephendolan** [winston/google_visualr#104]
Every time I run the `rspec` command in Rails 5.0 using RSpec-Rails 3.5, I get the following error:

```
/Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/helpers/view_helper.rb:7:in `block in <module:ViewHelper>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `class_eval'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/concern.rb:120:in `append_features'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `include'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `block (2 levels) in <class:Railtie>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/api.rb:145:in `<class:API>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/api.rb:88:in `<module:ActionController>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/api.rb:5:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `each'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/base.rb:263:in `<class:Base>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/base.rb:164:in `<module:ActionController>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.0.0/lib/action_controller/base.rb:5:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/action_view/test_case.rb:11:in `<class:TestCase>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/action_view/test_case.rb:10:in `<module:ActionView>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionview-5.0.0/lib/action_view/test_case.rb:8:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails/example/helper_example_group.rb:10:in `<module:HelperExampleGroup>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails/example/helper_example_group.rb:7:in `<module:Rails>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails/example/helper_example_group.rb:4:in `<module:RSpec>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails/example/helper_example_group.rb:3:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails/example.rb:4:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-rails-3.5.1/lib/rspec/rails.rb:13:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'
    from /Users/stephen/Repos/xpm/spec/rails_helper.rb:7:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/stephen/Repos/xpm/spec/models/user_spec.rb:1:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `load'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `each'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:100:in `setup'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:86:in `run'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:71:in `run'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/lib/rspec/core/runner.rb:45:in `invoke'
    from /Users/stephen/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rspec-core-3.5.2/exe/rspec:4:in `<top (required)>'
    from /Users/stephen/.rbenv/versions/2.3.1/bin/rspec:23:in `load'
    from /Users/stephen/.rbenv/versions/2.3.1/bin/rspec:23:in `<main>'
```

I was able to stop the error by adding an `if respond_to?(:helper_method)` wrapper around the `render_chart` method in the Visualr `app/helpers/view_helper.rb` file. Is this something I should make a pull request for, or something I need to fix with RSpec?

The error also occurs on the first pageload after restarting my Rails server.

**Comment by jiggneshhgohel** [comment]
In my case I am not even able to start my server:

```
jignesh@j-home-pc:/myapp$ rails s
=> Booting WEBrick
=> Rails 5.0.0.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
/.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/google_visualr-2.5.1/lib/google_visualr/app/helpers/view_helper.rb:7:in `block in <module:ViewHelper>': undefined method `helper_method' for ActionController::API:Class (NoMethodError)
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `class_eval'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/concern.rb:120:in `append_features'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `include'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/google_visualr-2.5.1/lib/google_visualr/app/railtie.rb:11:in `block (2 levels) in <class:Railtie>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:45:in `block in run_load_hooks'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in `each'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:44:in `run_load_hooks'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/actionpack-5.0.0.1/lib/action_controller/api.rb:145:in `<class:API>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/actionpack-5.0.0.1/lib/action_controller/api.rb:88:in `<module:ActionController>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/actionpack-5.0.0.1/lib/action_controller/api.rb:5:in `<top (required)>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `each'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/jbuilder-2.6.0/lib/jbuilder/railtie.rb:19:in `block in <class:Railtie>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/initializable.rb:30:in `run'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `call'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  from /.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/application.rb:352:in `initialize!'
  from /myapp/config/environment.rb:5:in `<top (required)>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/activesupport-5.0.0.1/lib/active_support/dependencies.rb:293:in `require'
  from /myapp/config.ru:3:in `block in <main>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/builder.rb:55:in `instance_eval'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/builder.rb:55:in `initialize'
  from /myapp/config.ru:in `new'
  from /myapp/config.ru:in `<main>'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/builder.rb:49:in `eval'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/builder.rb:49:in `new_from_string'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/builder.rb:40:in `parse_file'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/server.rb:318:in `build_app_and_options_from_config'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/server.rb:218:in `app'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/server.rb:59:in `app'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/rack-2.0.1/lib/rack/server.rb:353:in `wrapped_app'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/server.rb:124:in `log_to_stdout'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/server.rb:77:in `start'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
  from /.rvm/gems/ruby-2.3.1@myapp-rails-5/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

Is this WIP? If yes, when can we expect the fix for this to be released? Or for that matter when can we expect a new release compatible to work with Rails 5?

**Comment by stephendolan** [comment]
@jiggneshhgohel,

You can add this line to your Gemfile to use my forked version of the code:

`gem 'google_visualr',         github: 'stephendolan/google_visualr'`

**Comment by jiggneshhgohel** [comment]
@stephendolan Thanks a lot for that. I used it and my specs started running and also the server starts now. Thanks again.
